/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 18/01/2018 06:48:44
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI48_VALUE                          48000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     32000000
#define MX_SYSCLKFreq_VALUE                     32000000
#define MX_HCLKFreq_Value                       32000000
#define MX_FCLKCortexFreq_Value                 32000000
#define MX_AHBFreq_Value                        32000000
#define MX_APB1Freq_Value                       32000000
#define MX_APB2Freq_Value                       32000000
#define MX_48CLKFreq_Value                      32000000
#define MX_48RNGFreq_Value                      32000000
#define MX_48USBFreq_Value                      32000000
#define MX_ADCFreq_Value                        16000000
#define MX_I2C1Freq_Value                       32000000
#define MX_LCDFreq_Value                        37000
#define MX_LPUARTFreq_Value                     32000000
#define MX_LPTIMFreq_Value                      32000000
#define MX_PWRFreq_Value                        32000000
#define MX_USART1Freq_Value                     32000000
#define MX_USART2Freq_Value                     32000000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  4000000
#define MX_TimerFreq_Value                      32000000
#define MX_VCOOutputFreq_Value                  64000000
#define MX_WatchDogFreq_Value                   37000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB4 */
#define MX_PB4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_PinState                         GPIO_PIN_RESET
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA0 */
#define MX_PA0_Pin                              PA0
#define MX_PA0_GPIOx                            GPIOA
#define MX_PA0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA0_GPIO_Pin                         GPIO_PIN_0
#define MX_PA0_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */
